apiVersion: v1
kind: Namespace
metadata:
  name: pankaj-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cjoc-full-workload-access
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cjoc-full-access-binding
subjects:
  - kind: ServiceAccount
    name: cjoc
    namespace: cbci-test-pyadav-28912  # Replace with actual CJOC namespace
roleRef:
  kind: ClusterRole
  name: cjoc-full-workload-access
  apiGroup: rbac.authorization.k8s.io
